const BASE = 'http://52.202.202.227:8081'

export const register = `${BASE}/user/include`
export const login = `${BASE}/login`
export const profile = `${BASE}/profile`
export const target = `${BASE}/target/include`
export const alterRegister = `${BASE}/user/update`
export const newBet = `${BASE}/bet/include`
export const friend = `${BASE}/friend`
export const movements = `${BASE}/movements/include`
export const downloadCsvTarget = `${BASE}/targets/download`
export const downloadCsv = `${BASE}/movements/download`
export const update = `${BASE}/user/update`
export const updateTarget = `${BASE}/target/update`
export const action = `${BASE}/action/include`
export const getMovements = `${BASE}/movements/get`
export const movementsInitial = `${BASE}/movements/includeinitial`
export const friendSearch = `${BASE}/friend/search`
export const friendAdd = `${BASE}/friends/include`
